#!/bin/bash

# ==============================================================================
# Script Name: apply_patches.sh
# Description: Applies all patches in the 'patches' folder located at the AOSP root.
# Usage:       ./apply_patches.sh
# ==============================================================================

# Directory name containing the patches to be applied
PATCH_DIR="patches"

# 1. Check execution location
if [ ! -d "$PATCH_DIR" ]; then
    echo "❌ Error: '$PATCH_DIR' directory not found."
    echo "Please copy the patches folder generated by generate_patches.sh to this location."
    exit 1
fi

echo "========================================================"
echo "🛠️  Android 16 Security Patch Applier"
echo "   - Patch Source: $PATCH_DIR/"
echo "   - Target Root:  $(pwd)"
echo "========================================================"

# 2. Find and apply all .patch files in the patches folder
#    Find files one by one with 'find', sort them alphabetically, and process
find "$PATCH_DIR" -type f -name "*.patch" | sort | while read patch_file; do

    echo "🔧 Applying: $patch_file"

    # Explanation of patch command options:
    # -p0: Use the path in the patch file (system/vold/...) as is
    # -b : Back up the original file with the name '.orig' before applying
    # -N : Detect and skip already applied patches (forward-patch)
    # -r -: Do not generate a reject file, output to the screen

    patch -p0 -b -N < "$patch_file"

    # 3. Check execution result
    if [ $? -eq 0 ]; then
        echo "   ✅ Applied successfully."
    else
        echo "   ⚠️  Failed to apply or already applied."
    fi
    echo "--------------------------------------------------------"
done

echo "🎉 All patch application processes have been completed."
